# $Id: radioactive.mac 74917 2013-10-24 10:44:43Z ihrivnac $
#
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setNbOfAbsor  1
/testhadr/det/setAbsor 1 LaBr3_Ce 15 cm
/testhadr/det/setSizeYZ  15 cm
#
/run/initialize
#
/testhadr/gun/setDefault
/gun/particle neutron
#/gun/ion 11 22
/gun/energy 14.1 MeV
/gun/position 0 0 0 mm
#
/analysis/setFileName SABAT

/analysis/h1/set 1 1400 0. 14000 keV	#edep of Gamma
/analysis/h1/setAscii 1
/analysis/h1/set 2 145 0. 14500 keV	#ekin of Gamma
/analysis/h1/setAscii 2
/analysis/h1/set 3 145 0. 14500 keV	#ekin of Neutrons
/analysis/h1/setAscii 3
/analysis/h1/set 4 145 0. 14500 keV	#ekin of Neutrons generated in Detector
/analysis/h1/setAscii 4

/run/printProgress 100000
#
/run/beamOn 1000000
